initial_pose:
  x: -4.0
  y: -3.0
  yaw: 0.0

goals:
  - name: west_staging
    x: -2.40
    y: -3.00
    yaw: 0.0
  - name: center_staging
    x: 0.00
    y: -3.00
    yaw: 0.0
  - name: loading_dock
    x: 2.40
    y: -3.00
    yaw: 0.0
