initial_pose:
  x: -4.0
  y: -3.0
  yaw: 0.0

goals:
  - name: loading_dock
    x: 3.35
    y: -2.70
    yaw: 0.0
  - name: inspection_lane
    x: 3.25
    y: 2.65
    yaw: 1.57
  - name: right_aisle_return
    x: 3.30
    y: -2.55
    yaw: 3.14
